functionsDirectory = "/Users/matthewdean/Desktop/apex-backend/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/matthewdean/Desktop/apex-backend"
publishOrigin = "config"
functions = "/Users/matthewdean/Desktop/apex-backend/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
functions = "netlify/functions"

[functions]

[functions."*"]